version: '3.9'

services:

  postgres:
    container_name: currency
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=frozje
      - POSTGRES_PASSWORD=frozje
    volumes:
      - /data/postgresCurrency:/data/postgresCurrency
    networks:
      - postgres


volumes:
  postgres-data:
    driver: local


networks:
  postgres:
    driver: bridge
