version: '3.9'

services:
  rabbitmq:
    image: 'rabbitmq:3.10'
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - '5672:5672'
    volumes:
      - rabbitmq:/bitnami/rabbitmq


volumes:
  rabbitmq:
    driver: local
