"""typeFix

Revision ID: 09b7cf96b5f6
Revises: e85b42cecc3d
Create Date: 2022-09-03 17:38:35.030005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09b7cf96b5f6'
down_revision = 'e85b42cecc3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('order_type_key', 'order', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('order_type_key', 'order', ['type'])
    # ### end Alembic commands ###
