"""rename_amount

Revision ID: e85b42cecc3d
Revises: 4a6d7db789ce
Create Date: 2022-09-01 11:58:09.622502

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e85b42cecc3d'
down_revision = '4a6d7db789ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('price', sa.Float(), nullable=False))
    op.add_column('order', sa.Column('quantity', sa.Float(), nullable=False))
    op.create_unique_constraint(None, 'order', ['id'])
    op.drop_column('order', 'amount')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('amount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'order', type_='unique')
    op.drop_column('order', 'quantity')
    op.drop_column('order', 'price')
    # ### end Alembic commands ###
