"""add_balance

Revision ID: e0f7809a1503
Revises: fdfcaccc32e3
Create Date: 2023-03-21 19:19:59.451226

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e0f7809a1503'
down_revision = 'fdfcaccc32e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('balance', sa.DECIMAL(), nullable=True))
    op.drop_constraint('user_money_id_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'money_id')
    op.drop_table('money')
    op.create_foreign_key("wallet_id_user_id_fkey", 'wallet', 'user', ['user_id'], ['id'])
    op.create_foreign_key("wallet_id_currency_id_fkey", 'wallet', 'currency', ['currency_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("wallet_id_user_id_fkey", 'wallet', type_='foreignkey')
    op.drop_constraint("wallet_id_currency_id_fkey", 'wallet', type_='foreignkey')
    op.add_column('user', sa.Column('money_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_money_id_fkey', 'user', 'money', ['money_id'], ['id'])
    op.drop_column('user', 'balance')
    op.create_table('money',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='money_pkey'),
    sa.UniqueConstraint('id', name='uix_money_id')
    )
    # ### end Alembic commands ###
