version: '3.9'

services:
  postgres:
    container_name: user
    image: postgres:latest
    ports:
      - "5432:5432"
    expose:
      - "5432"
    restart: always
    environment:
      - POSTGRES_USER=frozje
      - POSTGRES_PASSWORD=frozje
    volumes:
      - /data/postgres:/data/postgres
    networks:
      - postgres


volumes:
  postgres-data:
    driver: local


networks:
  postgres:
    driver: bridge


