"""change_birthdate3

Revision ID: 386351859f0e
Revises: d336dbe21bd5
Create Date: 2022-05-06 15:16:25.418149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '386351859f0e'
down_revision = 'd336dbe21bd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'User', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'User', type_='unique')
    # ### end Alembic commands ###
