"""change_birthdate2

Revision ID: d336dbe21bd5
Revises: f10c48c8f75c
Create Date: 2022-05-06 15:12:13.588415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd336dbe21bd5'
down_revision = 'f10c48c8f75c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
