"""change_birthdate

Revision ID: f10c48c8f75c
Revises: 525c813532d7
Create Date: 2022-05-06 14:46:31.691705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f10c48c8f75c'
down_revision = '525c813532d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
