"""delete_nullable

Revision ID: 0cbceab72585
Revises: 68b913794188
Create Date: 2022-05-26 19:26:59.673879

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0cbceab72585'
down_revision = '68b913794188'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('currency_history', 'currency_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.alter_column('currency_history', 'price',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('currency_history', 'time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('tick', 'currency_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.alter_column('tick', 'tick_price',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('tick', 'time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_unique_constraint(None, 'tick', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tick', type_='unique')
    op.alter_column('tick', 'time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('tick', 'tick_price',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('tick', 'currency_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.alter_column('currency_history', 'time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('currency_history', 'price',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('currency_history', 'currency_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    # ### end Alembic commands ###
