"""Init3

Revision ID: 283af07012aa
Revises: b5835ed5e0d4
Create Date: 2022-05-11 19:08:45.312918

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '283af07012aa'
down_revision = 'b5835ed5e0d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'currency', ['id'])
    op.add_column('currency_history', sa.Column('currency_id', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_unique_constraint(None, 'currency_history', ['id'])
    op.create_foreign_key(None, 'currency_history', 'currency', ['currency_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'currency_history', type_='foreignkey')
    op.drop_constraint(None, 'currency_history', type_='unique')
    op.drop_column('currency_history', 'currency_id')
    op.drop_constraint(None, 'currency', type_='unique')
    # ### end Alembic commands ###
