"""fix_main_currency

Revision ID: 32dddaf7e8c8
Revises: 4095e9b0e350
Create Date: 2022-09-06 17:22:48.026416

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '32dddaf7e8c8'
down_revision = '4095e9b0e350'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'main_currency', ['id'])
    op.drop_column('main_currency', 'quantity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('main_currency', sa.Column('quantity', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'main_currency', type_='unique')
    # ### end Alembic commands ###
