"""intToFloat

Revision ID: 36d7172c5f2c
Revises: e04efbb854ba
Create Date: 2022-07-23 22:00:07.047058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36d7172c5f2c'
down_revision = 'e04efbb854ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
