"""add_price

Revision ID: 7b7cd57db54d
Revises: 283af07012aa
Create Date: 2022-05-12 14:41:03.338634

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7b7cd57db54d'
down_revision = '283af07012aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currency', sa.Column('price', sa.Integer(), nullable=False))
    op.add_column('currency_history', sa.Column('tick_price', postgresql.UUID(as_uuid=True), nullable=False))
    op.drop_column('currency_history', 'price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currency_history', sa.Column('price', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('currency_history', 'tick_price')
    op.drop_column('currency', 'price')
    # ### end Alembic commands ###
