"""delete_nullable

Revision ID: 8402da057de7
Revises: 0cbceab72585
Create Date: 2022-05-26 19:27:26.898491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8402da057de7'
down_revision = '0cbceab72585'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
