"""price_to_float

Revision ID: b15dcee0d38f
Revises: 7b7cd57db54d
Create Date: 2022-05-12 18:50:21.022403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b15dcee0d38f'
down_revision = '7b7cd57db54d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
