"""init_new

Revision ID: ed1e10c6c4bc
Revises: 32dddaf7e8c8
Create Date: 2022-10-09 17:45:26.908909

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ed1e10c6c4bc'
down_revision = '32dddaf7e8c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('main_currency')
    op.add_column('currency', sa.Column('type', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('currency', 'type')
    op.create_table('main_currency',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='main_currency_pkey'),
    sa.UniqueConstraint('id', name='main_currency_id_key')
    )
    # ### end Alembic commands ###
