"""amountToFloat

Revision ID: 53f6cfc00f2a
Revises: e74ead76ca5e
Create Date: 2022-07-05 17:55:50.348104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53f6cfc00f2a'
down_revision = 'e74ead76ca5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'wallet', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wallet', type_='unique')
    # ### end Alembic commands ###
