"""changeFloat

Revision ID: 845d8a805d0d
Revises: c6a439125b80
Create Date: 2022-07-07 09:56:34.556481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '845d8a805d0d'
down_revision = 'c6a439125b80'
branch_labels = None
depends_on = None


def upgrade():
    op.alter_column('wallet', 'amount',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
