"""added_quantity

Revision ID: c52c0517978f
Revises: d096521fbd96
Create Date: 2022-07-17 19:32:04.911444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c52c0517978f'
down_revision = 'd096521fbd96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallet', sa.Column('quantity', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallet', 'quantity')
    # ### end Alembic commands ###
