"""amountToFloat

Revision ID: c6a439125b80
Revises: 53f6cfc00f2a
Create Date: 2022-07-05 18:08:12.482407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6a439125b80'
down_revision = '53f6cfc00f2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
