version: '3.9'

services:

  postgres_user:
    container_name: user
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=user
    volumes:
      - /data/postgres-user:/data/postgres-user
    networks:
      - postgres_user


  postgres_currency:
    container_name: currency
    image: postgres:latest
    ports:
      - "5433:5432"
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=currency
    volumes:
      - /data/postgres-currency:/data/postgres-currency
    networks:
      - postgres_currency


  postgres_country:
    container_name: country
    image: postgres:latest
    ports:
      - "5434:5432"
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=country
    volumes:
      - /data/postgres-country:/data/postgres-country
    networks:
      - postgres_country

  postgres_order:
    container_name: order
    image: postgres:latest
    ports:
      - "5435:5432"
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=order
    volumes:
      - /data/postgres-order:/data/postgres-order
    networks:
      - postgres_order

  postgres_wallet:
    container_name: wallet
    image: postgres:latest
    ports:
      - "5436:5432"
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=wallet
    volumes:
      - /data/postgres-wallet:/data/postgres-wallet
    networks:
      - postgres_wallet


networks:
  postgres_user:
    driver: bridge
  postgres_currency:
    driver: bridge
  postgres_country:
    driver: bridge
  postgres_order:
    driver: bridge
  postgres_wallet:
    driver: bridge
